# Generated by Django 3.1 on 2020-08-19 15:33

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200819_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя')),
                ('secondname', models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адресс')),
                ('phone', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Телефон')),
                ('url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Ссылка на соц.сети')),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user',),
            managers=[
                ('objects', user.models.UserAccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('company', models.CharField(blank=True, max_length=256, null=True, verbose_name='Название компании')),
                ('category', models.CharField(blank=True, max_length=256, null=True, verbose_name='Род деятельности')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адресс')),
                ('fio', models.CharField(blank=True, max_length=1024, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Телефон')),
                ('url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Ссылка на сайт компании')),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user',),
            managers=[
                ('objects', user.models.UserAccountManager()),
            ],
        ),
    ]
